site_name: ProdManager documentation

repo_url: https://gitlab.com/prod-manager/prod-manager
repo_name: prod-manager
edit_uri: edit/master/docs/

theme:
  name: material
  font: false
  language: en
  logo: assets/prod-manager.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night

    - scheme: slate
      media: "(prefers-color-scheme: light)"
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/gitlab 
      link: https://gitlab.com/prod-manager/prod-manager
      name: prod-manager sources

copyright: Copyright &copy; 2022 Guillaume MARTINEZ (@Lunik)

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde