"""0.13.0

Revision ID: 0ec3e33b3896
Revises: 920bd288f8f8
Create Date: 2022-07-27 23:16:51.757785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec3e33b3896'
down_revision = '920bd288f8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_incident_external_reference'), 'incident', ['external_reference'], unique=False)
    op.create_index(op.f('ix_maintenance_external_reference'), 'maintenance', ['external_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_external_reference'), table_name='maintenance')
    op.drop_index(op.f('ix_incident_external_reference'), table_name='incident')
    # ### end Alembic commands ###
