"""0.17.0

Revision ID: 59afce3ef87c
Revises: 672f32454a2c
Create Date: 2022-11-04 13:30:21.187892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.sqlite.base import SQLiteDialect


# revision identifiers, used by Alembic.
revision = '59afce3ef87c'
down_revision = '672f32454a2c'
branch_labels = None
depends_on = None

old_maintenance_status_options = ('SCHEDULED', 'IN_PROGRESS', 'SUCCEED', 'FAILED')
new_maintenance_status_options = ('SCHEDULED', 'IN_PROGRESS', 'SUCCEED', 'FAILED', 'CANCELED')

old_maintenance_status = sa.Enum(*old_maintenance_status_options, name='maintenancestatus')
new_maintenance_status = sa.Enum(*new_maintenance_status_options, name='maintenancestatus')
tmp_maintenance_status = sa.Enum(*new_maintenance_status_options, name='_maintenancestatus')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not isinstance(op.get_bind().dialect, SQLiteDialect):
        tmp_maintenance_status.create(op.get_bind(), checkfirst=False)
        op.execute("""
            ALTER TABLE maintenance
            ALTER COLUMN status TYPE _maintenancestatus
            USING status::text::_maintenancestatus
        """)
        old_maintenance_status.drop(op.get_bind(), checkfirst=False)
        new_maintenance_status.create(op.get_bind(), checkfirst=False)
        op.execute("""
            ALTER TABLE maintenance
            ALTER COLUMN status TYPE maintenancestatus
            USING status::text::maintenancestatus
        """)
        tmp_maintenance_status.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not isinstance(op.get_bind().dialect, SQLiteDialect):
        tmp_maintenance_status.create(op.get_bind(), checkfirst=False)
        op.execute("""
            ALTER TABLE maintenance
            ALTER COLUMN status TYPE _maintenancestatus
            USING status::text::_maintenancestatus
        """)
        new_maintenance_status.drop(op.get_bind(), checkfirst=False)
        old_maintenance_status.create(op.get_bind(), checkfirst=False)
        op.execute("""
            ALTER TABLE maintenance
            ALTER COLUMN status TYPE maintenancestatus
            USING status::text::maintenancestatus
        """)
        tmp_maintenance_status.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
