"""0.3.0

Revision ID: 5c889d53d173
Revises: 647227471a57
Create Date: 2022-06-07 22:52:38.546822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c889d53d173'
down_revision = '647227471a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance', 'service_planned_status', new_column_name='service_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance', 'service_status', new_column_name='service_planned_status')
    # ### end Alembic commands ###
