"""0.8.0

Revision ID: 60556090b264
Revises: aa5f2f1eeb17
Create Date: 2022-06-22 18:40:08.102974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.sqlite.base import SQLiteDialect


# revision identifiers, used by Alembic.
revision = '60556090b264'
down_revision = 'aa5f2f1eeb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_event', sa.Column('internal', sa.Boolean(), nullable=False))
    op.add_column('maintenance_event', sa.Column('internal', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_event', 'internal')
    op.drop_column('incident_event', 'internal')
    # ### end Alembic commands ###
