"""0.15.0

Revision ID: 672f32454a2c
Revises: 0ec3e33b3896
Create Date: 2022-08-31 13:37:50.683296

"""
import re

from alembic import op
import sqlalchemy as sa

from ProdManager.models.Monitor import Monitor


# revision identifiers, used by Alembic.
revision = '672f32454a2c'
down_revision = '0ec3e33b3896'
branch_labels = None
depends_on = None

datadog_url_regex = re.compile(r".*/(\d+)$")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor', sa.Column('external_reference', sa.String(), nullable=True))
    op.add_column('monitor', sa.Column('integration', sa.String(), nullable=True))

    print("Migrating legacy Datadog monitors")
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    monitors = session.query(Monitor).filter(Monitor.external_link.like("%datadoghq%"))

    for monitor in monitors:
        monitor_id = datadog_url_regex.match(monitor.external_link).group(1)
        print(f"Migrating : {monitor} - {monitor.external_link} -> {monitor_id}")

        monitor.integration = "datadog"
        monitor.external_reference = monitor_id

    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor', 'integration')
    op.drop_column('monitor', 'external_reference')

    # TODO back migrate monitors

    # ### end Alembic commands ###
