"""0.12.0

Revision ID: 920bd288f8f8
Revises: 15ce6bf2e389
Create Date: 2022-07-21 18:21:21.486459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920bd288f8f8'
down_revision = '15ce6bf2e389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('external_link', sa.String(), nullable=True))
    op.add_column('maintenance', sa.Column('external_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance', 'external_link')
    op.drop_column('incident', 'external_link')
    # ### end Alembic commands ###
