"""0.0.0

Revision ID: 96401e5e2911
Revises: 
Create Date: 2022-06-06 15:18:39.072446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96401e5e2911'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app',
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app')
    # ### end Alembic commands ###
