"""0.5.0

Revision ID: aa5f2f1eeb17
Revises: 0e57f0ab2101
Create Date: 2022-06-10 19:06:53.220389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5f2f1eeb17'
down_revision = '0e57f0ab2101'
branch_labels = None
depends_on = None

monitor_status = sa.Enum('OK', 'WARNING', 'ALERT', name='monitorstatus')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('external_link', sa.String(), nullable=True),
    sa.Column('status', monitor_status, nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['scope.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('service', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('status', sa.VARCHAR(length=8), nullable=False))
    op.drop_table('monitor')
    monitor_status.drop(op.get_bind())
    # ### end Alembic commands ###
