"""0.21.0

Revision ID: f137dd84b5a0
Revises: 5c0b69e6ce7e
Create Date: 2023-03-25 19:21:44.226770

"""
from uuid import uuid4
from alembic import op
import sqlalchemy as sa

from ProdManager.models.AppConfig import AppConfig

# revision identifiers, used by Alembic.
revision = 'f137dd84b5a0'
down_revision = '5c0b69e6ce7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )

    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    session.add(AppConfig(uuid=str(uuid4())))

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_config')
    # ### end Alembic commands ###
