apiVersion: v1
kind: Secret
metadata:
  labels:
    app: prod-manager
    component: app
  name: prod-manager
data:
  PM_SECRET_KEY: Y2hhbmdlaXQ=
  PM_DATABASE_URI: cG9zdGdyZXNxbDovL3Byb2RtYW5hZ2VyOmNoYW5nZWl0QHByb2QtbWFuYWdlci1kYXRhYmFzZS9wcm9kbWFuYWdlcg==
  PM_REDIS_URI: cmVkaXM6Ly9wcm9kLW1hbmFnZXItcmVkaXM=