---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod-manager
    component: app
  name: prod-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-manager
      component: app
  template:
    metadata:
      labels:
        app: prod-manager
        component: app
    spec:
      initContainers:
      - image: registry.gitlab.com/prod-manager/prod-manager:latest
        imagePullPolicy: Always
        name: database
        command: ["make", "database-upgrade"]
        envFrom:
        - secretRef:
            name: prod-manager
        resources:
          requests:
            cpu: 50m
            memory: 20M
          limits:
            cpu: 250m
            memory: 100M
      containers:
      - image: registry.gitlab.com/prod-manager/prod-manager:latest
        imagePullPolicy: Always
        name: app
        env:
          - name: PORT
            value: "8080"
        envFrom:
        - secretRef:
            name: prod-manager
        resources:
          requests:
            cpu: 50m
            memory: 100M
          limits:
            cpu: 500m
            memory: 150M
