---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: prod-manager
    component: app
  name: prod-manager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-manager
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
