---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prod-manager
    component: database
  name: prod-manager-database
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: default
