apiVersion: v1
kind: Secret
metadata:
  labels:
    app: prod-manager
    component: database
  name: prod-manager-database
data:
  POSTGRES_PASSWORD: Y2hhbmdlaXQ=
  POSTGRES_USER: cHJvZG1hbmFnZXI=
  POSTGRES_DB: cHJvZG1hbmFnZXI=