---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prod-manager
    component: database
  name: prod-manager-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-manager
      component: database
  template:
    metadata:
      labels:
        app: prod-manager
        component: database
    spec:
      containers:
      - image: postgres
        name: database
        envFrom:
        - secretRef:
            name: prod-manager-database
        resources:
          requests:
            cpu: 50m
            memory: 50M
          limits:
            cpu: 500m
            memory: 200M
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prod-manager-database
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Paris
            type: File
