---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prod-manager
    component: proxy
  name: prod-manager-proxy
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  _;
    
        location /static {
            root   /usr/share/nginx/html;
            index  index.html;
        }
    
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass http://prod-manager:80/;
        }
    }