---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prod-manager
    component: redis
  name: prod-manager-redis
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
